spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog_demo?characterEncoding=UTF-8&serverTimezone=GMT%2b8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false&connectTimeout=30000000
    username: blog_demo
    password: blog_demo123
server:
  port: 9527
